"use client";

import React, { useState, useEffect } from "react";
import { useContract } from "@/context/ContractContext";
import { Sparkles, Clock, CheckCircle2, Copy, Download, Loader2, Calendar, FileText } from "lucide-react";
import { toast } from "sonner";

export default function SummaryPage() {
  const { selectedContract: contract, loading: contextLoading, isUsingMockData } = useContract();
  const [loading, setLoading] = useState(true);
  
  useEffect(() => {
    if (!contextLoading) {
      setLoading(false);
    }
  }, [contextLoading]);

  if (contextLoading || loading) {
    return (
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-8 sm:p-12 flex flex-col items-center justify-center space-y-4">
        <div className="w-12 h-12 rounded-full bg-violet-50 flex items-center justify-center">
          <Loader2 className="w-6 h-6 text-violet-600 animate-spin" />
        </div>
        <div className="text-center">
          <h3 className="text-base font-semibold text-slate-900 mb-1">Generating AI Summary...</h3>
          <p className="text-slate-500 text-xs max-w-sm">We are compiling clauses, critical deadlines, and risk factors from the uploaded contract.</p>
        </div>
      </div>
    );
  }

  if (!contract) {
    return (
      <div className="max-w-md mx-auto text-center py-20 space-y-4">
        <div className="w-16 h-16 bg-zinc-100 rounded-full flex items-center justify-center mx-auto text-slate-400">
          <FileText className="w-8 h-8" />
        </div>
        <h2 className="text-xl font-semibold text-slate-900">No contract selected</h2>
        <p className="text-slate-500 text-sm">Please upload a contract or select one from the dashboard to begin summary generation.</p>
      </div>
    );
  }

  const summary = contract.aiSummary;

  if (!summary) return null;

  const handleCopy = () => {
    if (summary.executiveSummary) {
      navigator.clipboard.writeText(summary.executiveSummary);
      toast.success("Summary narrative copied to clipboard!");
    } else {
      toast.error("No summary text available to copy");
    }
  };

  const handleDownloadPDF = () => {
    if (isUsingMockData) {
      toast.success("PDF analysis report downloaded! (mock mode)");
      return;
    }
    const BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
    window.open(`${BASE_URL}/api/contracts/${contract.id}/pdf`, "_blank");
  };

  const handleDownloadDocx = () => {
    if (isUsingMockData) {
      toast.success("Word Redline report downloaded! (mock mode)");
      return;
    }
    const BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
    window.open(`${BASE_URL}/api/contracts/${contract.id}/docx`, "_blank");
  };

  const downloadCalendarICS = () => {
    if (!summary.deadlines || summary.deadlines.length === 0) {
      toast.error("No deadlines found to add to calendar");
      return;
    }
    
    let icsContent = "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//ContractIQ//Deadline Calendar//EN\n";
    
    summary.deadlines.forEach((deadline) => {
      const dateRaw = deadline.date.replace(/-/g, "").trim();
      const dateStr = dateRaw.length === 8 ? dateRaw : "20261231";
      
      icsContent += "BEGIN:VEVENT\n";
      icsContent += `SUMMARY:ContractIQ Deadline: ${deadline.title} (${contract.name.replace(".pdf", "")})\n`;
      icsContent += `DTSTART;VALUE=DATE:${dateStr}\n`;
      icsContent += `DTEND;VALUE=DATE:${dateStr}\n`;
      icsContent += `DESCRIPTION:Contract obligation deadline for ${contract.name}. Generated by ContractIQ.\n`;
      icsContent += "STATUS:CONFIRMED\n";
      icsContent += "END:VEVENT\n";
    });
    
    icsContent += "END:VCALENDAR";
    
    const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `${contract.name.replace(".pdf", "")}_deadlines.ics`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success("Calendar invite (.ics) downloaded successfully!");
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8 pb-12">
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold text-slate-900">AI Summary</h1>
          <p className="text-slate-500 text-sm">{contract.name.replace(".pdf", "")} — auto-generated plain-English analysis</p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button 
            onClick={handleCopy}
            className="flex items-center gap-2 px-3 py-1.5 bg-white border border-slate-200 text-slate-600 rounded-lg text-sm font-semibold hover:bg-slate-50 transition-all duration-200 shadow-sm cursor-pointer"
          >
            <Copy className="w-4 h-4" />
            Copy Summary
          </button>
          <button 
            onClick={handleDownloadPDF}
            className="flex items-center gap-2 px-3 py-1.5 bg-white border border-slate-200 text-slate-600 rounded-lg text-sm font-semibold hover:bg-slate-50 transition-all duration-200 shadow-sm cursor-pointer"
          >
            <Download className="w-4 h-4" />
            Download PDF
          </button>
          <button 
            onClick={handleDownloadDocx}
            className="flex items-center gap-2 px-3 py-1.5 bg-white border border-slate-200 text-slate-600 rounded-lg text-sm font-semibold hover:bg-slate-50 transition-all duration-200 shadow-sm cursor-pointer"
          >
            <FileText className="w-4 h-4 text-blue-500" />
            Download Word
          </button>
          <button 
            onClick={downloadCalendarICS}
            className="flex items-center gap-2 px-3 py-1.5 bg-blue-50 hover:bg-blue-100 text-blue-700 border border-blue-200/60 rounded-lg text-sm font-semibold transition-all duration-200 shadow-sm cursor-pointer"
          >
            <Calendar className="w-4 h-4" />
            Sync Calendar
          </button>
          <div className="flex items-center gap-2 px-3 py-1.5 bg-violet-50 text-violet-700 rounded-lg border border-violet-200/60 font-semibold text-sm">
            <Sparkles className="w-4 h-4" />
            AI Generated
          </div>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden animate-in fade-in slide-in-from-bottom-2 duration-500">
        
        {/* Executive Summary */}
        {summary.executiveSummary && (
          <div className="p-5 sm:p-8 border-b border-slate-100 bg-slate-50/50">
            <h3 className="text-xs font-bold text-slate-400 tracking-wider mb-3 uppercase">Executive Summary</h3>
            <p className="text-slate-700 text-sm sm:text-base leading-relaxed font-medium">
              {summary.executiveSummary}
            </p>
          </div>
        )}

        <div className="p-5 sm:p-8 space-y-12">
          {/* Key Obligations */}
          <div>
            <h3 className="text-xs font-bold text-slate-400 tracking-wider mb-4 uppercase">Key Obligations</h3>
            <ul className="space-y-4">
              {summary.obligations.map((obs) => (
                <li key={obs.id} className="flex items-start gap-3">
                  <span className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-2 shrink-0" />
                  <span className="text-slate-700 text-sm leading-relaxed">{obs.text}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Key Deadlines */}
          <div>
            <h3 className="text-xs font-bold text-slate-400 tracking-wider mb-4 uppercase">Key Deadlines</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {summary.deadlines.map((deadline) => (
                  <div 
                    key={deadline.id} 
                    className={`p-4 rounded-xl border flex items-start gap-3 transition-colors duration-200 hover:shadow-sm ${
                      deadline.isCritical 
                        ? "border-amber-300 bg-amber-50/30" 
                        : "bg-slate-50/50 border-slate-100"
                    }`}
                  >
                    <Clock className={`w-4 h-4 mt-0.5 shrink-0 ${deadline.isCritical ? "text-amber-500" : "text-slate-400"}`} />
                    <div>
                      <p className="text-xs text-slate-500 mb-1 font-medium">{deadline.title}</p>
                      <p className={`font-bold text-sm ${deadline.isCritical ? "text-amber-700" : "text-slate-800"}`}>
                        {deadline.date}
                      </p>
                    </div>
                  </div>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12">
            {/* Financial Commitments */}
            <div>
              <h3 className="text-xs font-bold text-slate-400 tracking-wider mb-4 uppercase">Financial Commitments</h3>
              <div className="space-y-0">
                {summary.financialCommitments.map((fin) => (
                  <div key={fin.id} className="flex flex-wrap gap-2 justify-between py-3 border-b border-slate-100 last:border-0 hover:bg-slate-50 transition-colors px-2 rounded -mx-2">
                    <span className="text-slate-700 text-sm">{fin.name}</span>
                    <span className="font-bold text-slate-900 text-sm">{fin.value}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Renewal Terms */}
            {summary.renewalTerms && (
              <div>
                <h3 className="text-xs font-bold text-slate-400 tracking-wider mb-4 uppercase">Renewal Terms</h3>
                <ul className="space-y-3">
                  {summary.renewalTerms.map((term, idx) => (
                    <li key={idx} className="flex items-start gap-3">
                      <span className="text-slate-400 mt-0.5 shrink-0">•</span>
                      <span className="text-slate-700 text-sm leading-relaxed">{term}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12">
            {/* Termination Conditions */}
            {summary.terminationConditions && (
              <div>
                <h3 className="text-xs font-bold text-slate-400 tracking-wider mb-4 uppercase">Termination Conditions</h3>
                <ul className="space-y-3">
                  {summary.terminationConditions.map((cond, idx) => (
                    <li key={idx} className="flex items-start gap-3">
                      <span className="text-slate-400 mt-0.5 shrink-0">•</span>
                      <span className="text-slate-700 text-sm leading-relaxed">{cond}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Top Risks */}
            {summary.topRisks && (
              <div>
                <h3 className="text-xs font-bold text-rose-500 tracking-wider mb-4 uppercase">Top Risks</h3>
                <ul className="space-y-3">
                  {summary.topRisks.map((risk, idx) => (
                    <li key={idx} className="flex items-start gap-3 bg-rose-50/50 p-2.5 rounded-lg border border-rose-100/50">
                      <span className="text-rose-500 font-bold mt-0.5 shrink-0">!</span>
                      <span className="text-rose-950 text-sm leading-relaxed">{risk}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>

          {/* Recommended Next Steps */}
          {summary.recommendedNextSteps && (
            <div className="pt-6 border-t border-zinc-100">
              <h3 className="text-xs font-bold text-teal-600 tracking-wider mb-4 uppercase flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4" /> Recommended Next Steps
              </h3>
              <div className="grid gap-3">
                {summary.recommendedNextSteps.map((step, idx) => (
                  <div key={idx} className="flex items-center gap-3 bg-teal-50/50 border border-teal-100/60 rounded-lg p-3 hover:bg-teal-50 transition-colors duration-200 cursor-default">
                    <div className="w-6 h-6 rounded-full bg-teal-100 text-teal-700 flex items-center justify-center shrink-0 text-xs font-bold">
                      {idx + 1}
                    </div>
                    <span className="text-teal-900 text-sm font-medium">{step}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Reviewer Notes Section */}
      <ReviewerNotesCard contractId={contract.id} initialNotes={contract.notes || ""} />
    </div>
  );
}

interface ReviewerNotesCardProps {
  contractId: string;
  initialNotes: string;
}

function ReviewerNotesCard({ contractId, initialNotes }: ReviewerNotesCardProps) {
  const [notes, setNotes] = useState(initialNotes);
  const [isSaving, setIsSaving] = useState(false);
  const [isDirty, setIsDirty] = useState(false);
  const { refreshContracts } = useContract();

  useEffect(() => {
    setNotes(initialNotes);
    setIsDirty(false);
  }, [initialNotes]);

  const handleSave = async () => {
    setIsSaving(true);
    try {
      const { updateContractNotes } = await import("@/lib/api");
      await updateContractNotes(contractId, notes);
      setIsDirty(false);
      toast.success("Reviewer notes saved successfully");
      await refreshContracts();
    } catch (err) {
      toast.error("Failed to save reviewer notes");
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden p-6 sm:p-8 space-y-4">
      <div>
        <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wider">Reviewer Notes & Annotations</h3>
        <p className="text-slate-500 text-xs mt-1">Add custom legal notes, negotiation progress updates, or internal guidance for this contract. Saved notes are persisted in the database.</p>
      </div>
      
      <textarea
        value={notes}
        onChange={(e) => {
          setNotes(e.target.value);
          setIsDirty(true);
        }}
        placeholder="Type reviewer notes here..."
        className="w-full min-h-[120px] p-3 text-sm text-slate-700 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
        disabled={isSaving}
      />

      <div className="flex justify-end">
        <button
          onClick={handleSave}
          disabled={!isDirty || isSaving}
          className={`px-4 py-2 rounded-lg text-sm font-semibold transition-all shadow-sm ${
            isDirty && !isSaving
              ? "bg-[#2563eb] hover:bg-blue-600 text-white cursor-pointer active:scale-95"
              : "bg-slate-50 border border-slate-200 text-slate-400 cursor-not-allowed"
          }`}
        >
          {isSaving ? "Saving..." : "Save Notes"}
        </button>
      </div>
    </div>
  );
}
