"""
LLM Client service using Groq API.

Manages Groq SDK client instance, handles retries, rate limits, and timeouts.
Dispatches prompt templates to Groq for contract summaries, clause extraction,
risk analysis, and chatbot responses.
"""

import os
import time
from typing import Optional, Type, TypeVar
from functools import lru_cache

from groq import Groq
from dotenv import load_dotenv
from pydantic import BaseModel, ValidationError

load_dotenv()

MODEL_NAME = "llama-3.3-70b-versatile"

T = TypeVar("T", bound=BaseModel)

@lru_cache(maxsize=1)
def get_llm_client() -> Groq:
    """Initialize and cache the official Groq client.

    Returns:
        A cached Groq client instance.

    Raises:
        ValueError: If GROQ_API_KEY is not set.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise ValueError(
            "GROQ_API_KEY is not set. "
            "Please add it to your .env file."
        )
    return Groq(api_key=api_key)


def generate_response(prompt: str, json_mode: bool = False) -> str:
    """Generate a text response using Groq completions API with retry logic.

    Args:
        prompt: The fully constructed prompt.
        json_mode: Whether to request JSON output format.

    Returns:
        The text response generated by Llama 3.3.

    Raises:
        RuntimeError: If Groq API request repeatedly fails.
    """
    client = get_llm_client()
    
    retry_delays = [1.0, 2.0, 4.0]
    last_exception = None

    for i, delay in enumerate(retry_delays + [0.0]):
        try:
            kwargs = {
                "model": MODEL_NAME,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.2,
            }
            if json_mode:
                kwargs["response_format"] = {"type": "json_object"}

            completion = client.chat.completions.create(**kwargs)
            content = completion.choices[0].message.content
            if content is None:
                raise RuntimeError("Received empty response from Groq.")
            return content
        except Exception as e:
            last_exception = e
            # If we have retries remaining, wait with backoff
            if i < len(retry_delays):
                time.sleep(delay)
            else:
                break

    raise RuntimeError(
        f"Groq API error after {len(retry_delays) + 1} attempts: {last_exception}"
    )


def generate_json_response(prompt: str, model_class: Type[T]) -> T:
    """Generate a JSON response and validate it against a Pydantic model.
    Retries once on validation error with warning instructions.

    Args:
        prompt: The prompt to send.
        model_class: The Pydantic model class to validate and parse into.

    Returns:
        An instance of model_class.
    """
    try:
        content = generate_response(prompt, json_mode=True)
        return model_class.model_validate_json(content)
    except (ValidationError, Exception) as e:
        # Retry once with validation warning
        retry_prompt = (
            f"{prompt}\n\n"
            f"WARNING: Your previous response was invalid or did not match the required schema: {str(e)}.\n"
            f"Please correct the JSON format and return ONLY a valid JSON object matching the schema."
        )
        content = generate_response(retry_prompt, json_mode=True)
        return model_class.model_validate_json(content)
